name: Gh-Pages

on:
  push:
    branches: [ main ]
    
permissions:
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter config --enable-web
        shell: bash
        working-directory: ${{inputs.workingDir}}
      - run: flutter build web --release --base-href="/"
        shell: bash
        working-directory: ${{inputs.workingDir}}
      
#       - name: Checkout
#         uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: ${{inputs.workingDir}}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
